language: python
python:
- 3.5
- 3.6
dist: trusty
matrix:
  include:
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3 make
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
install:
  - pip install -r requirements-dev.txt
  - pip install -e .
  - pip freeze
script:
  - set -eo pipefail
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
